name: Build

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**.c'
      - '**.h'
      - 'Makefile'
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make VERSION_TYPE=none
