name: Test

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**.c'
      - '**.h'
      - 'Makefile'
      - '**.yml'
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Make test
      run: make bin/test1

    - name: Run test
      run: make test
