name: Test

on:
  push:
    branches: [ "dev" ]
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**.c'
      - '**.h'
      - 'Makefile'
      - '**.yml'
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Test
      run: make test
